### ISSUE TITLE
Transfer incomplete Blender 2.80

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/community-plugins-socket#2]
http://issues.makehumancommunity.org/issues/111

**Comment by Aranuvir** [comment]
That issue had already been addressed? Please make sure to use the latest versions of MakeHuman, socket and blender-plugins...

**Comment by rwbaer** [comment]
You are likely correct that I got behind, but I had registration issues when updating.  Don't know if that is Blender, me or the plugin itself.
http://issues.makehumancommunity.org/issues/111#note-1

**Comment by joepal1976** [comment]
Assuming this is no longer relevant
